### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by fujin** [ftomassetti/JavaCC2ANTLR#6]
Greetings,

I am wondering if you can make this code available under an open source license.

Thanks for any insight!

**Comment by ftomassetti** [comment]
Yes, we can release it under Apache License V2.0. Perhaps you may consider making a PR for adding the LICENSE file and a line in the README: that would speed up the transition

**Comment by fujin** [comment]
Much appreciated. Opened PR #7.

**Comment by ftomassetti** [comment]
Thank you, this is now solved
